# Generated by Django 3.1 on 2020-09-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexPromotionBanner',
            new_name='ProductInfo',
        ),
    ]
